### ISSUE TITLE
N918809 / บริษัท ไบต์อาร์ค จำกัด / รายการสินทรัพย์แสดที่เมนูการจัดการสินทรัพย์ ทั้งที่ได้ทำการเปลื่ยนหมวดหมู่เป็นค่าใช้จ่ายแล้ว 

### ISSUE THREAD

**Issue by Phassaray** [flowaccount/Tech_Support#10]
แก้ไขรายการรายการบันทึกที่หน้า EXP2021010003 เป็นค่าใช้จ่ายแล้ว ในหน้าทะเบียนสินทรัพย์รายการยังค้างอยู่ไม่แก้ตาม / เชิญ Help แล้ว
![image](https://user-images.githubusercontent.com/75408080/111152500-62584100-85c3-11eb-950b-d2c422627800.png)
![image](https://user-images.githubusercontent.com/75408080/111152563-700dc680-85c3-11eb-91c8-a17bf4bbb4f4.png)
![image](https://user-images.githubusercontent.com/75408080/111152581-756b1100-85c3-11eb-8a60-4ebcac655715.png)

**Comment by pachara-flow** [comment]
สาเหตุ เกิดจากมีการ reset company expense เลยหายไป แต่ยังไม่มี feature reset asset มัส แก้แล้วต้อง deploy ทั้ง intranet และ data-management-api
