### ISSUE TITLE
N521246 / หจก.สิมา โฮลดิ้ง /  ระบบบันทึกบัญชีการจ่ายชำระเงิน ซ้ำกัน 

### ISSUE THREAD

**Issue by Phassaray** [flowaccount/Tech_Support#8]
N521246 / หจก.สิมา โฮลดิ้ง / เอกสารRI2020120014 บันทึกบัญชีจ่ายชำระเงิน  PV2020120039 ซ้ำกับ PV2020120222  
 และ เอกสาร RI2020120027 บันทึกบัญชีจ่ายชำระเงิน PV2020120053 ซ้ำกับ PV2020120221 
![image](https://user-images.githubusercontent.com/75408080/111028100-05c01f00-8427-11eb-9df3-cc51bcc648a4.png)
![image](https://user-images.githubusercontent.com/75408080/111028106-0f498700-8427-11eb-9b7e-79f62d42a417.png)

**Comment by pachara-flow** [comment]
แก้ไขให้แล้วครับ
